# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto

require 'google/protobuf'


descriptor_data = "\n\x11\x61\x64\x64ressbook.proto\x12\x08tutorial\"-\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rphone_numbers\x18\x02 \x03(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Tutorial
  Person = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tutorial.Person").msgclass
end
